# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2526f424851356aca215d49ac38a317f4e7d8da197eba45f5469c496683614720f660518ac3d5cbfad1f9dc1edded9155f7d4a658451a187f3a1a04c0d31991f

test:
  secret_key_base: 93aa5da291bb5ae41c6fef6777c90ee0db73c559d62fbe87303089bfad358b4a98432aafa199ff34750ff0ecf97de54d9e40a9d01e67c8c5e84bcf6e7395d139

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
